# Borrowed from pycares/cyares

name: Release Wheels

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build_wheels:
    uses: ./.github/workflows/run-cibuildwheel.yml
    with:
      fail-fast: true

  build_sdist:
    uses: ./.github/workflows/run-sdist.yml

  # TODO: Soon as I can figure out how aio-libs handles wheel releases in the release folder I will try doing this again.
  # for now automatically accepting PRS from dependabot will suffice.
  # upload_to_github_release_page:
  #   needs: [build_wheels, build_sdist]
  #   if: github.event_name == 'release' && github.event.action == 'published'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v8
  #       with:
  #         path: dist
  #         merge-multiple: true
  #     - run: ls -lR dist
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         files: *.whl
          
        
  upload_pypi:
    needs: [build_wheels, build_sdist]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          merge-multiple: true
      - run: ls -lR dist
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          # TODO: Move to trusted Publishing after winloop 0.1.91
          password: ${{ secrets.PYPI_PASSWORD }}
